### ISSUE TITLE
input format for hdr model

### ISSUE THREAD

**Issue by dex1990** [mgharbi/hdrnet#3]
Hi!
    How can i convert the input data(RGB) to your custom YUV format?
Thanks!

**Comment by Zealoe** [comment]
the same question

**Comment by jxwjasonborne** [comment]
Hi~
For the HDR+ task, in the test stage, what is the format of input image to the hdrnet ?  Original hdr data or 8-bit tone mapped RGB image ? Specifically,  for the first image in the fourth row of figure 14 in the original paper. Thx!

**Comment by mgharbi** [comment]
If I recall correctly, the input's format is linear 16-bit and is specific to the HDR+ dataset and the HDR+ pipeline. It corresponds to the image produced by the "align and merge step" of the HDR+ pipeline.

I will do my best to add a working test pair to this repo soon. 

I unfortunately cannot release the HDR+ dataset used for training. You will need to contact the authors of that paper to obtain a copy of it: http://www.hdrplusdata.org/
