### ISSUE TITLE
Where is the pretrained model?

### ISSUE THREAD

**Issue by Zealoe** [mgharbi/hdrnet#4]
![image](https://user-images.githubusercontent.com/30797481/29151418-9056af7c-7db3-11e7-8f99-2315d096ab7f.png)
I can't find the dictionary. Thanks.

**Comment by happydenn** [comment]
Since this issue was closed. Did you find the pretrained model? Thanks!

**Comment by happydenn** [comment]
Nevermind. Found pretrained models from the Project Page. Thanks.
